apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitor.fullname" . }}-collector
  labels:
    {{- include "monitor.labels" . | nindent 4 }}
    app: collector
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: collector
      protocol: TCP
      name: collector
  selector:
    {{- include "monitor.selectorLabels" . | nindent 4 }}
    app: collector
