// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: const.proto

package c

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ROLE int32

const (
	ROLE_CUSTOMER ROLE = 0
	ROLE_HANDYMAN ROLE = 1
	ROLE_ADMIN    ROLE = 2
)

// Enum value maps for ROLE.
var (
	ROLE_name = map[int32]string{
		0: "CUSTOMER",
		1: "HANDYMAN",
		2: "ADMIN",
	}
	ROLE_value = map[string]int32{
		"CUSTOMER": 0,
		"HANDYMAN": 1,
		"ADMIN":    2,
	}
)

func (x ROLE) Enum() *ROLE {
	p := new(ROLE)
	*p = x
	return p
}

func (x ROLE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ROLE) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[0].Descriptor()
}

func (ROLE) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[0]
}

func (x ROLE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ROLE.Descriptor instead.
func (ROLE) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{0}
}

type SERVICE_STATUS int32

const (
	SERVICE_STATUS_SERVICE_ACTIVE   SERVICE_STATUS = 0
	SERVICE_STATUS_SERVICE_INACTIVE SERVICE_STATUS = 1
)

// Enum value maps for SERVICE_STATUS.
var (
	SERVICE_STATUS_name = map[int32]string{
		0: "SERVICE_ACTIVE",
		1: "SERVICE_INACTIVE",
	}
	SERVICE_STATUS_value = map[string]int32{
		"SERVICE_ACTIVE":   0,
		"SERVICE_INACTIVE": 1,
	}
)

func (x SERVICE_STATUS) Enum() *SERVICE_STATUS {
	p := new(SERVICE_STATUS)
	*p = x
	return p
}

func (x SERVICE_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SERVICE_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[1].Descriptor()
}

func (SERVICE_STATUS) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[1]
}

func (x SERVICE_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SERVICE_STATUS.Descriptor instead.
func (SERVICE_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{1}
}

type OTP_TYPE int32

const (
	OTP_TYPE_REGISTER             OTP_TYPE = 0
	OTP_TYPE_FORGOT_PASSWORD      OTP_TYPE = 1
	OTP_TYPE_CHANGE_MAIL          OTP_TYPE = 2
	OTP_TYPE_CHANGE_MAIL_AND_PASS OTP_TYPE = 3
)

// Enum value maps for OTP_TYPE.
var (
	OTP_TYPE_name = map[int32]string{
		0: "REGISTER",
		1: "FORGOT_PASSWORD",
		2: "CHANGE_MAIL",
		3: "CHANGE_MAIL_AND_PASS",
	}
	OTP_TYPE_value = map[string]int32{
		"REGISTER":             0,
		"FORGOT_PASSWORD":      1,
		"CHANGE_MAIL":          2,
		"CHANGE_MAIL_AND_PASS": 3,
	}
)

func (x OTP_TYPE) Enum() *OTP_TYPE {
	p := new(OTP_TYPE)
	*p = x
	return p
}

func (x OTP_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OTP_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[2].Descriptor()
}

func (OTP_TYPE) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[2]
}

func (x OTP_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OTP_TYPE.Descriptor instead.
func (OTP_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{2}
}

type ORDER_STATUS int32

const (
	ORDER_STATUS_PENDING   ORDER_STATUS = 0
	ORDER_STATUS_CONNECTED ORDER_STATUS = 1
	ORDER_STATUS_REJECTED  ORDER_STATUS = 2
	ORDER_STATUS_CANCELED  ORDER_STATUS = 3
	ORDER_STATUS_COMPLETED ORDER_STATUS = 4
)

// Enum value maps for ORDER_STATUS.
var (
	ORDER_STATUS_name = map[int32]string{
		0: "PENDING",
		1: "CONNECTED",
		2: "REJECTED",
		3: "CANCELED",
		4: "COMPLETED",
	}
	ORDER_STATUS_value = map[string]int32{
		"PENDING":   0,
		"CONNECTED": 1,
		"REJECTED":  2,
		"CANCELED":  3,
		"COMPLETED": 4,
	}
)

func (x ORDER_STATUS) Enum() *ORDER_STATUS {
	p := new(ORDER_STATUS)
	*p = x
	return p
}

func (x ORDER_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ORDER_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[3].Descriptor()
}

func (ORDER_STATUS) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[3]
}

func (x ORDER_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ORDER_STATUS.Descriptor instead.
func (ORDER_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{3}
}

type ACCOUNT_STATUS int32

const (
	ACCOUNT_STATUS_ACTIVE   ACCOUNT_STATUS = 0
	ACCOUNT_STATUS_INACTIVE ACCOUNT_STATUS = 1
)

// Enum value maps for ACCOUNT_STATUS.
var (
	ACCOUNT_STATUS_name = map[int32]string{
		0: "ACTIVE",
		1: "INACTIVE",
	}
	ACCOUNT_STATUS_value = map[string]int32{
		"ACTIVE":   0,
		"INACTIVE": 1,
	}
)

func (x ACCOUNT_STATUS) Enum() *ACCOUNT_STATUS {
	p := new(ACCOUNT_STATUS)
	*p = x
	return p
}

func (x ACCOUNT_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACCOUNT_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[4].Descriptor()
}

func (ACCOUNT_STATUS) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[4]
}

func (x ACCOUNT_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACCOUNT_STATUS.Descriptor instead.
func (ACCOUNT_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{4}
}

type SORT_QUERY int32

const (
	SORT_QUERY_DEFAULT SORT_QUERY = 0
	SORT_QUERY_REQUEST SORT_QUERY = 1
	SORT_QUERY_REVIEW  SORT_QUERY = 2
)

// Enum value maps for SORT_QUERY.
var (
	SORT_QUERY_name = map[int32]string{
		0: "DEFAULT",
		1: "REQUEST",
		2: "REVIEW",
	}
	SORT_QUERY_value = map[string]int32{
		"DEFAULT": 0,
		"REQUEST": 1,
		"REVIEW":  2,
	}
)

func (x SORT_QUERY) Enum() *SORT_QUERY {
	p := new(SORT_QUERY)
	*p = x
	return p
}

func (x SORT_QUERY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SORT_QUERY) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[5].Descriptor()
}

func (SORT_QUERY) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[5]
}

func (x SORT_QUERY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SORT_QUERY.Descriptor instead.
func (SORT_QUERY) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{5}
}

type QUERY_CATEGORY_ADMIN int32

const (
	QUERY_CATEGORY_ADMIN_NO        QUERY_CATEGORY_ADMIN = 0 // cant use default because it declared above
	QUERY_CATEGORY_ADMIN_ADVERTISE QUERY_CATEGORY_ADMIN = 1
	QUERY_CATEGORY_ADMIN_GROUP     QUERY_CATEGORY_ADMIN = 2
)

// Enum value maps for QUERY_CATEGORY_ADMIN.
var (
	QUERY_CATEGORY_ADMIN_name = map[int32]string{
		0: "NO",
		1: "ADVERTISE",
		2: "GROUP",
	}
	QUERY_CATEGORY_ADMIN_value = map[string]int32{
		"NO":        0,
		"ADVERTISE": 1,
		"GROUP":     2,
	}
)

func (x QUERY_CATEGORY_ADMIN) Enum() *QUERY_CATEGORY_ADMIN {
	p := new(QUERY_CATEGORY_ADMIN)
	*p = x
	return p
}

func (x QUERY_CATEGORY_ADMIN) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QUERY_CATEGORY_ADMIN) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[6].Descriptor()
}

func (QUERY_CATEGORY_ADMIN) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[6]
}

func (x QUERY_CATEGORY_ADMIN) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QUERY_CATEGORY_ADMIN.Descriptor instead.
func (QUERY_CATEGORY_ADMIN) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{6}
}

type REGISTRATION_PROCESS int32

const (
	REGISTRATION_PROCESS_DONE   REGISTRATION_PROCESS = 0
	REGISTRATION_PROCESS_STEP_1 REGISTRATION_PROCESS = 1
	REGISTRATION_PROCESS_STEP_2 REGISTRATION_PROCESS = 2
	REGISTRATION_PROCESS_STEP_3 REGISTRATION_PROCESS = 3
)

// Enum value maps for REGISTRATION_PROCESS.
var (
	REGISTRATION_PROCESS_name = map[int32]string{
		0: "DONE",
		1: "STEP_1",
		2: "STEP_2",
		3: "STEP_3",
	}
	REGISTRATION_PROCESS_value = map[string]int32{
		"DONE":   0,
		"STEP_1": 1,
		"STEP_2": 2,
		"STEP_3": 3,
	}
)

func (x REGISTRATION_PROCESS) Enum() *REGISTRATION_PROCESS {
	p := new(REGISTRATION_PROCESS)
	*p = x
	return p
}

func (x REGISTRATION_PROCESS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (REGISTRATION_PROCESS) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[7].Descriptor()
}

func (REGISTRATION_PROCESS) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[7]
}

func (x REGISTRATION_PROCESS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use REGISTRATION_PROCESS.Descriptor instead.
func (REGISTRATION_PROCESS) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{7}
}

type SORT_TRANSACTION int32

const (
	SORT_TRANSACTION_THIS_WEEK    SORT_TRANSACTION = 0
	SORT_TRANSACTION_LAST_1_WEEK  SORT_TRANSACTION = 1
	SORT_TRANSACTION_LAST_2_WEEKS SORT_TRANSACTION = 2
	SORT_TRANSACTION_LAST_3_WEEKS SORT_TRANSACTION = 3
	SORT_TRANSACTION_LAST_MONTH   SORT_TRANSACTION = 4
	SORT_TRANSACTION_ALL_TIME     SORT_TRANSACTION = 5
)

// Enum value maps for SORT_TRANSACTION.
var (
	SORT_TRANSACTION_name = map[int32]string{
		0: "THIS_WEEK",
		1: "LAST_1_WEEK",
		2: "LAST_2_WEEKS",
		3: "LAST_3_WEEKS",
		4: "LAST_MONTH",
		5: "ALL_TIME",
	}
	SORT_TRANSACTION_value = map[string]int32{
		"THIS_WEEK":    0,
		"LAST_1_WEEK":  1,
		"LAST_2_WEEKS": 2,
		"LAST_3_WEEKS": 3,
		"LAST_MONTH":   4,
		"ALL_TIME":     5,
	}
)

func (x SORT_TRANSACTION) Enum() *SORT_TRANSACTION {
	p := new(SORT_TRANSACTION)
	*p = x
	return p
}

func (x SORT_TRANSACTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SORT_TRANSACTION) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[8].Descriptor()
}

func (SORT_TRANSACTION) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[8]
}

func (x SORT_TRANSACTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SORT_TRANSACTION.Descriptor instead.
func (SORT_TRANSACTION) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{8}
}

type STATUS_VERIFY_REFERRAL_CODE int32

const (
	STATUS_VERIFY_REFERRAL_CODE_NONE      STATUS_VERIFY_REFERRAL_CODE = 0
	STATUS_VERIFY_REFERRAL_CODE_VERIFYING STATUS_VERIFY_REFERRAL_CODE = 1
	STATUS_VERIFY_REFERRAL_CODE_DENY      STATUS_VERIFY_REFERRAL_CODE = 2
	STATUS_VERIFY_REFERRAL_CODE_ACCEPT    STATUS_VERIFY_REFERRAL_CODE = 3
)

// Enum value maps for STATUS_VERIFY_REFERRAL_CODE.
var (
	STATUS_VERIFY_REFERRAL_CODE_name = map[int32]string{
		0: "NONE",
		1: "VERIFYING",
		2: "DENY",
		3: "ACCEPT",
	}
	STATUS_VERIFY_REFERRAL_CODE_value = map[string]int32{
		"NONE":      0,
		"VERIFYING": 1,
		"DENY":      2,
		"ACCEPT":    3,
	}
)

func (x STATUS_VERIFY_REFERRAL_CODE) Enum() *STATUS_VERIFY_REFERRAL_CODE {
	p := new(STATUS_VERIFY_REFERRAL_CODE)
	*p = x
	return p
}

func (x STATUS_VERIFY_REFERRAL_CODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STATUS_VERIFY_REFERRAL_CODE) Descriptor() protoreflect.EnumDescriptor {
	return file_const_proto_enumTypes[9].Descriptor()
}

func (STATUS_VERIFY_REFERRAL_CODE) Type() protoreflect.EnumType {
	return &file_const_proto_enumTypes[9]
}

func (x STATUS_VERIFY_REFERRAL_CODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STATUS_VERIFY_REFERRAL_CODE.Descriptor instead.
func (STATUS_VERIFY_REFERRAL_CODE) EnumDescriptor() ([]byte, []int) {
	return file_const_proto_rawDescGZIP(), []int{9}
}

var File_const_proto protoreflect.FileDescriptor

var file_const_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x2a, 0x2d, 0x0a, 0x04, 0x52, 0x4f, 0x4c, 0x45, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x41,
	0x4e, 0x44, 0x59, 0x4d, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49,
	0x4e, 0x10, 0x02, 0x2a, 0x3a, 0x0a, 0x0e, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x52,
	0x56, 0x49, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x2a,
	0x58, 0x0a, 0x08, 0x4f, 0x54, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x4f, 0x52,
	0x47, 0x4f, 0x54, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12,
	0x18, 0x0a, 0x14, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x41,
	0x4e, 0x44, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x10, 0x03, 0x2a, 0x55, 0x0a, 0x0c, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43,
	0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10,
	0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x04,
	0x2a, 0x2a, 0x0a, 0x0e, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x2a, 0x32, 0x0a, 0x0a,
	0x53, 0x4f, 0x52, 0x54, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45,
	0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x10, 0x02,
	0x2a, 0x38, 0x0a, 0x14, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f,
	0x52, 0x59, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x4f, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x41, 0x44, 0x56, 0x45, 0x52, 0x54, 0x49, 0x53, 0x45, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x02, 0x2a, 0x44, 0x0a, 0x14, 0x52, 0x45,
	0x47, 0x49, 0x53, 0x54, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45,
	0x53, 0x53, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x54, 0x45, 0x50, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x45, 0x50,
	0x5f, 0x32, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x45, 0x50, 0x5f, 0x33, 0x10, 0x03,
	0x2a, 0x74, 0x0a, 0x10, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x48, 0x49, 0x53, 0x5f, 0x57, 0x45, 0x45,
	0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x31, 0x5f, 0x57, 0x45,
	0x45, 0x4b, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x32, 0x5f, 0x57,
	0x45, 0x45, 0x4b, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x33,
	0x5f, 0x57, 0x45, 0x45, 0x4b, 0x53, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x41, 0x53, 0x54,
	0x5f, 0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x4c, 0x4c, 0x5f,
	0x54, 0x49, 0x4d, 0x45, 0x10, 0x05, 0x2a, 0x4c, 0x0a, 0x1b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x5f, 0x52, 0x45, 0x46, 0x45, 0x52, 0x52, 0x41, 0x4c,
	0x5f, 0x43, 0x4f, 0x44, 0x45, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x43, 0x45,
	0x50, 0x54, 0x10, 0x03, 0x42, 0x05, 0x5a, 0x03, 0x2e, 0x2f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_const_proto_rawDescOnce sync.Once
	file_const_proto_rawDescData = file_const_proto_rawDesc
)

func file_const_proto_rawDescGZIP() []byte {
	file_const_proto_rawDescOnce.Do(func() {
		file_const_proto_rawDescData = protoimpl.X.CompressGZIP(file_const_proto_rawDescData)
	})
	return file_const_proto_rawDescData
}

var file_const_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_const_proto_goTypes = []interface{}{
	(ROLE)(0),                        // 0: const.ROLE
	(SERVICE_STATUS)(0),              // 1: const.SERVICE_STATUS
	(OTP_TYPE)(0),                    // 2: const.OTP_TYPE
	(ORDER_STATUS)(0),                // 3: const.ORDER_STATUS
	(ACCOUNT_STATUS)(0),              // 4: const.ACCOUNT_STATUS
	(SORT_QUERY)(0),                  // 5: const.SORT_QUERY
	(QUERY_CATEGORY_ADMIN)(0),        // 6: const.QUERY_CATEGORY_ADMIN
	(REGISTRATION_PROCESS)(0),        // 7: const.REGISTRATION_PROCESS
	(SORT_TRANSACTION)(0),            // 8: const.SORT_TRANSACTION
	(STATUS_VERIFY_REFERRAL_CODE)(0), // 9: const.STATUS_VERIFY_REFERRAL_CODE
}
var file_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_const_proto_init() }
func file_const_proto_init() {
	if File_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_const_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_const_proto_goTypes,
		DependencyIndexes: file_const_proto_depIdxs,
		EnumInfos:         file_const_proto_enumTypes,
	}.Build()
	File_const_proto = out.File
	file_const_proto_rawDesc = nil
	file_const_proto_goTypes = nil
	file_const_proto_depIdxs = nil
}
