// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package model

import (
	"context"
	"github.com/aqaurius6666/chatservice/src/internal/db"
	"github.com/aqaurius6666/chatservice/src/services/mailservice"
	"github.com/aqaurius6666/chatservice/src/services/redis"
	"github.com/aqaurius6666/chatservice/src/services/twilloclient"
	"github.com/sirupsen/logrus"
	"testing"
)

// Injectors from model.mock.go:

func NewMockModel(ctx context.Context, logger *logrus.Logger, dsn db.DBDsn, t *testing.T) (Server, error) {
	serverRepo, err := db.NewMockRepo(ctx, logger, dsn)
	if err != nil {
		return nil, err
	}
	twilio := twilloclient.MockClient(t)
	redisImpl := &redis.RedisImpl{}
	serviceGRPC := &mailservice.ServiceGRPC{}
	serverModel := &ServerModel{
		Ctx:    ctx,
		Logger: logger,
		Repo:   serverRepo,
		Twillo: twilio,
		Redis:  redisImpl,
		Mail:   serviceGRPC,
	}
	return serverModel, nil
}
