apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatservice.fullname" . }}
  labels:
    {{- include "chatservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "chatservice.selectorLabels" . | nindent 4 }}
