version: "3.7"
networks:
  main:
    name: go-go


services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: --requirepass 19102001
    environment:
      - REDIS_PASSWORD=19102001
    networks:
      - main
  # unleash-db:
  #   image: postgres:13
  #   volumes:
  #     - unleashdb:/var/lib/postgresql
  #   environment:
  #     POSTGRES_DB: "db"
  #     POSTGRES_HOST_AUTH_METHOD: "trust"
  #   networks:
  #     - main
  # unleash:
  #   image: unleashorg/unleash-server
  #   ports:
  #     - "4242:4242"
  #   environment:
  #     DATABASE_URL: "postgres://postgres:unleash@unleash-db/postgres"
  #     DATABASE_SSL: "false"
  #   depends_on:
  #     - unleash-db
  #   networks:
  #     - main
  # chatservice-db:
  #   image: cockroachdb/cockroach:v21.1.6
  #   ports:
  #     - "20000:26257"
  #   command: start-single-node --insecure
  #   volumes:
  #     - "chatservice-db:/cockroach/cockroach-data"
  #   networks:
  #     - main
  chatservice:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "../../:/app"
      - $HOME/go:/go
    ports:
      - "9093:8080"
      - "50050:50051"
      - "2346:2345"
    command:
      - /bin/sh
      - -c
      - |
        air
    env_file: .env
    networks:
      - main
# volumes:
  # unleashdb:
  # chatservice-db:
