apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authservice.fullname" . }}-env
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
data:
{{ range .Files.Lines ".env" }}
  {{- include "helpers.convert-env" (dict "line" . )  | indent 2}}
{{ end }}