scrape_configs:
  - job_name: 'authservice'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:7071']
  - job_name: 'apiservice'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:7070']