version: "3.7"
networks:
  main:
    name: go-go


services:
  # unleash-db:
  #   image: postgres:13
  #   volumes:
  #     - unleashdb:/var/lib/postgresql
  #   environment:
  #     POSTGRES_DB: "db"
  #     POSTGRES_HOST_AUTH_METHOD: "trust"
  #   networks:
  #     - main
  # unleash:
  #   image: unleashorg/unleash-server
  #   ports:
  #     - "4242:4242"
  #   environment:
  #     DATABASE_URL: "postgres://postgres:unleash@unleash-db/postgres"
  #     DATABASE_SSL: "false"
  #   depends_on:
  #     - unleash-db
  #   networks:
  #     - main
  authservice-db:
    image: cockroachdb/cockroach:v21.1.6
    ports:
      - "50010:26257"
    command: start-single-node --insecure
    volumes:
      - "authservice-db:/cockroach/cockroach-data"
    networks:
      - main
  authservice:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "../../:/app"
      - $HOME/go:/go
    ports:
      - "50011:50051"
      # - "2345:2345"
    depends_on:
      - authservice-db
    command:
      - /bin/sh
      - -c
      - |
        air
    env_file: .env
    networks:
      - main
volumes:
  # unleashdb:
  authservice-db:
