// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package db

import (
	"context"
	"github.com/aqaurius6666/chatservice/src/internal/db/cockroach"
	cockroach2 "github.com/aqaurius6666/go-utils/database/cockroach"
	"github.com/sirupsen/logrus"
)

// Injectors from server.repo.mock.go:

func NewMockRepo(ctx context.Context, logger *logrus.Logger, dsn DBDsn) (ServerRepo, error) {
	db, err := ConnectGorm(dsn)
	if err != nil {
		return nil, err
	}
	dbInterfaces := cockroach.InterfacesProvider()
	cdbRepository := cockroach2.CDBRepository{
		Db:         db,
		Logger:     logger,
		Context:    ctx,
		Interfaces: dbInterfaces,
	}
	serverCDBRepo := &cockroach.ServerCDBRepo{
		CDBRepository: cdbRepository,
	}
	return serverCDBRepo, nil
}
