# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  repositories:
  - repository: test-go
    type: git
    name: Handyman/test-go
    trigger:
      branches:
        include:
        - test

trigger:
- main

pool:
  name: Builder

steps:
- checkout: test-go
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
