apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loadbalancer.fullname" . }}-conf
  labels:
    {{- include "loadbalancer.labels" . | nindent 4 }}
data:
  {{ $apiservice :=  "http://apiservice/api"  -}}
  {{ $chatservice :=  "http://chatservice/api/chat"  -}}
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    events {
      worker_connections  4096;  ## Default: 1024
    }
    http {
      resolver 127.0.0.1:53 ipv6=off valid=10s;
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=7d use_temp_path=off;
      server {
        listen  80;
        server_tokens off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        client_max_body_size 1000M;
        gzip on;
        gzip_proxied any;
        gzip_comp_level 4;
        gzip_types text/css application/javascript image/svg+xml;
        set $apiservice {{ $apiservice }};
        set $chatservice {{ $chatservice }};
        location ~ ^\/api\/chat(.*)$ {
          proxy_pass $chatservice$1$is_args$args;
          proxy_set_header  Host $http_host;
        }
        location ~ ^\/api(.*)$  {
          proxy_pass $apiservice$1$is_args$args;
          proxy_set_header  Host $http_host;
        }
      }
    }